services:
  - type: web
    name: MyApp
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: true
      - key: ADMIN_CHAT_ID
        sync: true